/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class phpjava_MsgQ */

#ifndef _Included_phpjava_MsgQ
#define _Included_phpjava_MsgQ
#ifdef __cplusplus
extern "C" {
#endif
#undef phpjava_MsgQ_KEY
#define phpjava_MsgQ_KEY 537006640L
/*
 * Class:     phpjava_MsgQ
 * Method:    msgget
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_phpjava_MsgQ_msgget
  (JNIEnv *, jclass, jint);

/*
 * Class:     phpjava_MsgQ
 * Method:    msgsnd
 * Signature: (II[BI)I
 */
JNIEXPORT jint JNICALL Java_phpjava_MsgQ_msgsnd
  (JNIEnv *, jclass, jint, jint, jbyteArray, jint);

/*
 * Class:     phpjava_MsgQ
 * Method:    msgrcv
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_phpjava_MsgQ_msgrcv
  (JNIEnv *, jclass, jint, jbyteArray, jint, jint);

/*
 * Class:     phpjava_MsgQ
 * Method:    msgclose
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_phpjava_MsgQ_msgclose
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
